# Generated by Django 6.0.5 on 2026-05-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('sign_out_time', models.DateTimeField(blank=True, null=True)),
                ('fee_charged', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('receiver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('receiver_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('receiver_nin', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
