# Generated by Django 6.0.5 on 2026-05-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck'), ('personal_car', 'Personal Car'), ('taxi', 'Taxi'), ('coaster', 'Coaster'), ('boda_boda', 'Boda-boda')], max_length=20)),
                ('number_plate', models.CharField(max_length=6)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('arrival_time', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('nin_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_signed_out', models.BooleanField(default=False)),
            ],
        ),
    ]
